### ISSUE TITLE
error installing kadot

### ISSUE THREAD

**Issue by saumyarshah9697** [the-new-sky/Kadot#2]
pip install kadot
Collecting kadot
  Using cached Kadot-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saumya\AppData\Local\Temp\pip-build-jx_xqoci\kadot\setup.py", line 8, in <module>
        long_description= open('README', 'r').read(),
      File "C:\Users\Saumya\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2094: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Saumya\AppData\Local\Temp\pip-build-jx_xqoci\kadot\

**Comment by loristns** [comment]
This is an encoding issue due to Windows. I will see how to solve that. 😉

**Comment by loristns** [comment]
I just submitted a patch on Pypi (called [0.1.6b](https://pypi.python.org/pypi/Kadot/0.1.6b)), can you try it ?

**Comment by saumyarshah9697** [comment]
yes sure, in a minute.

**Comment by saumyarshah9697** [comment]
in a minute. I closed the issue by mistake.

**Comment by saumyarshah9697** [comment]
pip install kadot
Collecting kadot
  Using cached Kadot-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saumya\AppData\Local\Temp\pip-build-wcg20grw\kadot\setup.py", line 8, in <module>
        long_description= open('README', 'r').read(),
      File "C:\Users\Saumya\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2094: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Saumya\AppData\Local\Temp\pip-build-wcg20grw\kadot\

**Comment by saumyarshah9697** [comment]
oh wait, it works fine. But not through pip. I had to manually download, unzip and "python setup.py install" it.. Thanks a lot.

**Comment by loristns** [comment]
Perfect.

The problem was that Pypi doesn't support my version naming and consider the non-patched version like the latest. The successful command is `pip install kadot=0.1.6b`. This problem will be automatically patched when I will release 0.1.7.
